export const GET_CATS_REQUEST = "GET_CATS_REQUEST";
export const GET_CATS_SUCCESS = "GET_CATS_SUCCESS";
export const GET_CATS_FAILURE = "GET_CATS_FAILURE";

export const GET_CATS_CATEGORIES_REQUEST = "GET_CATS_CATEGORIES_REQUEST";
export const GET_CATS_CATEGORIES_SUCCESS = "GET_CATS_CATEGORIES_SUCCESS";
export const GET_CATS_CATEGORIES_FAILURE = "GET_CATS_CATEGORIES_FAILURE";
